### PR TITLE
Add user-visible matlab exvivo model

### PR DESCRIPTION
**Pull request by cfhammill**
Hi, 

Given the interest in ex-vivo modelling (issue #5), I thought it might be useful to expose the model such that users can use `AMICO_SetModel( 'NODDI_EXVIVO' )`. 

Maybe @daducci or @dicemt can suggest how to tweak the regularization params to get a fit that approximates the original NODDI toolbox.

Cheers,

Chris

### CODE REVIEW

**Comment by daducci** [comment]
We actually never tested the `ex-vivo` as we don't have such data for NODDI. Do you notice any difference, though, between AMICO (without the DOT compartment) and NODDI? In our experience, we never observed any big difference at least with the ActiveAx model

**Comment by daducci** [comment]
Hi Chris,

I moved the matlab code to an independent repository ([here](https://github.com/daducci/AMICO_matlab)). In fact, we mainly work and develop new features to the python version and we then decided to split the two projects into separate repositories. In particular, tha matlab repo won;t be actively maintained but, if you're interested, you could still push your modifications to it. What do you think?

**Comment by cfhammill** [comment]
Hi Alessandro, I was originally noting very large differences between AMICO and NODDI, although that may have been an artifact stemming from me using camino's fsl2scheme without the bscale parameter. So I'll need to go back and check again. It's good to hear the the project is splitting. I would prefer to use the python implementation if you now consider it robust enough for general use. If so I'll just close this pull request. 

Cheers and thanks again,

Chris

**Comment by daducci** [comment]
AMICO is still under active development, so I cannot tell you what is more stable. But our development is focused on the python branch, so every bug fix, enhancement etc etc will be developed only in this code from now on.
Still, as some people are still using the matlab version, we decided to keep the project open and let it follow its own path.

Concerning the differences you noticed between AMICO and NODDI, I would be really interested to hear your feedback from you!

**Pull request closed without merging**
