### PR TITLE
ENH: Add option to force b-values to pre-defined shells

### PR DESCRIPTION
**Pull request by cookpa**
Also

  - Add explanatory output
  - Warn if change in b-values is large
  - Write scheme file values to 6 decimal places

### CODE REVIEW

**Comment by cookpa** [comment]
Hi,

Setting the b-values to their nominal values makes a big difference in the speed of kernel generation, as you said.

It also affects the fitting when the kernels are re-used, because there are small differences in the actual b-values between acquisitions, even when the underlying scheme is the same. 

The output is much more consistent when the b-values are fixed to the nominal shells.

**Comment by daducci** [comment]
Nice contribution, I think it can be really useful for many.
Thanks a lot @cookpa!

**Comment by cookpa** [comment]
Happy to help, thank you for writing this great software. I am getting much better results and closer agreement with the NODDI toolbox now.

**Comment by daducci** [comment]
Closes issue #10

**Pull request merged**
