### PR TITLE
Adding requirements files and setup_requires

### PR DESCRIPTION
**Pull request by frheault**
Adding requirements file (to facilitate setup using `pip install -r requirements.txt`) and adding this information to the setup.py so a future `pip install amico` would be possible (amico already exist on pypi, so it would be something like `pip install amico-daducci`. I did a small test and it seems to work (Don't worry the package is still called `amico` in python)

These additions are useful for easy installation, especially for current work in scilpy.
To be compliant with pypi I had to add a `LICENSE.txt` file. I used the same as COMMIT, if that is not the license you want I can switch it easily with something else.

(A similar PR will be done in the COMMIT repository)

### CODE REVIEW

**Comment by daducci** [comment]
Thanks @frheault, this is definitely needed! I'm not sure which is the best license to be used and I don't have any constraint. I checked the license of DIPY, whihch we use, and it is BSD; perhaps we should change to BSD to give more freedom? Lastly, as for the name, what about `dmri-amico` and `dmri-commit` instead? This is more general and does not link only to my name as the project is not only mine but we develop it as a team. Can you make the change? Then I can try uploading it to PYPI

**Comment by frheault** [comment]
@daducci I think switching to BSD would make it easier to incorporate COMMIT in other projects. That would be the perfect moment to switch AMICO/COMMIT to BSD.

I will change the name to dmri-amico and dmri-commit, these package names are available. Switching the package name only affects the `pip install`, but import and usage remain the same (`import amico`).

Do you want me to simply copy the dipy license (and replace the word dipy with AMICO) ? if not, you can send me a text file with the right text in it.
Is `dmri-amico` your final choice, changing it is easy, but after a while, it's too late for that once it's "distributed".

**Comment by daducci** [comment]
This license choice looks perfect, let's go with it!
I like the names with `dmri` instead of `daducci` as it is more general, but if you have any suggestion I am open to any option

**Comment by frheault** [comment]
I did the modification (on both AMICO and COMMIT)
If you want to try it, you can register at https://pypi.org/account/register/
then you will need this: `pip install twine`
then from a folder containing my code (or the future master post-merging)
```
python setup.py sdist
twine upload dist/*
```
The second command will ask for your PyPI account. And voilà.

SOURCE: https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56

**Comment by daducci** [comment]
I did a test, but I get errors with the installation of spams (very common). In fact, if you install it with `pip install spams` (as done by the requirements) then there is a known error in OSX which happens only with version 2.6.1 but not with 2.6. However, only 2.6.1 is available on PYPI. I've just sent an email to the developers of SPAMS asking to upload to PYPI also the version 2.6 (the one without the error); let's see if they respond. otherwise, is it possible to specify in the requirements to install a specific version from an url? For instance, the following works: `pip install http://spams-devel.gforge.inria.fr/hitcounter2.php\?file\=file/36849/spams-python3-v2.6-2017-06-06.tar.gz`

**Comment by frheault** [comment]
@daducci I can also simply point to `spams>=2.6.0`
I don't think there is a big difference between both.
Using a specific URL can work, but then would prevent an easy install of scilpy that includes commit which includes amico which includes spams with an URL.

I think the safest option is simply to use 2.6.0 rather than 2.6.1. Unless you are aware of a major bug that influences AMICO that was fixed in some way by 2.6.1?

**Comment by daducci** [comment]
Unfortunately, there's no SPAMS 2.6 on PYPI, but only the version 2.6.1 (which generates the compilation problem with `openmp` on OSX). SO we need first to have the version 2.6 on PYPI (I already sent an email to the developers) and, also, force AMICO to install `spams==2.6.0`

**Comment by frheault** [comment]
We will have to wait for an answer, when using a ZIP/URL the setup crashes because it does not interpret the spams package dependencies in the correct order and so numpy is missing at runtime. This would prevent AMICO from installing easily using PyPi...

I will keep looking for a workaround, but the easiest solution would be that they add the OSx friendly version to PyPi, I hope they are still maintaining the package !

**Comment by arnaudbore** [comment]
@frheault can you give it a try with sklearn lasso version: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html

I would be more than happy to get rid of spams :+1:

**Pull request merged**
